cd and lighthouse config modified

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -59,8 +59,8 @@ jobs:
 
           if [ $FAILED -eq 1 ]; then
             echo "One or more smoke tests failed, rolling back..."
-            PREV_DEPLOY=$(vercel list --token $VERCEL_TOKEN --prod --limit 2 | tail -n1 | awk '{print $1}')
-            vercel rollback $PREV_DEPLOY --token $VERCEL_TOKEN
+            PREV_DEPLOY=$(npx vercel list --token $VERCEL_TOKEN --prod --limit 2 | tail -n1 | awk '{print $1}')
+            npx vercel rollback $PREV_DEPLOY --token $VERCEL_TOKEN
             exit 1
           fi
 
@@ -78,8 +78,8 @@ jobs:
           lhci autorun --collect.url=https://mmeletricarservice.it || FAILED=1
 
           if [ $FAILED -eq 1 ]; then
-          echo "Lighthouse assertions failed, rolling back..."
-          PREV_DEPLOY=$(vercel list --token $VERCEL_TOKEN --prod --limit 2 | tail -n1 | awk '{print $1}')
-          vercel rollback $PREV_DEPLOY --token $VERCEL_TOKEN
-          exit 1
+            echo "Lighthouse assertions failed, rolling back..."
+            PREV_DEPLOY=$(npx vercel list --token $VERCEL_TOKEN --prod --limit 2 | tail -n1 | awk '{print $1}')
+            npx vercel rollback $PREV_DEPLOY --token $VERCEL_TOKEN
+            exit 1
           fi
